apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue-deployment
  labels:
    app: flask
spec:
  replicas: 3
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 3
  #   maxUnavailable: 1
  #   intervalSeconds: 5
  #   updatePeriodSeconds: 5
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: kubgroup/p1_kubgroup:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"